version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: candidate-match-frontend
    ports:
      - "8080:80" # Map container port 80 to host port 8080
    environment:
      # Environment variables are passed to the container
      # But React, being client-side, needs them at build time.
      # See the explanation below for how to handle this.
      - NODE_ENV=development