# .github/workflows/frontend-ci.yml
name: Frontend CI

# This workflow runs on pushes to any branch and on pull requests targeting the main branch.
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  # This job runs on push and PR to check for basic correctness
  build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build

  # This job runs ONLY on pull requests to provide an AI code review
  gemini-pull-request-review:
    name: Gemini PR Review
    runs-on: ubuntu-latest
    # Run this job only on pull requests, but not from dependabot
    if: github.event_name == 'pull_request_target' && github.actor != 'dependabot[bot]'
    permissions:
      pull-requests: write # Required to post the review comment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to check out the specific PR branch
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get PR Diff
        id: pr_diff
        run: |
          # Fetch the target branch
          git fetch origin ${{ github.event.pull_request.base.ref }}
          # Get the diff
          diff_output=$(git diff origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }})
          # Escape for JSON and set as output
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$diff_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # Add your Workload Identity Federation credentials here
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Call Gemini to Review PR
        id: gemini_review
        uses: google-github-actions/run-gcloud@v1
        with:
          command: |
            # Read the prompt template from the file
            PROMPT_TEMPLATE=$(cat pr_review_prompt.txt)
            # Get the diff from the previous step's output
            DIFF='${{ steps.pr_diff.outputs.diff }}'

            # Replace the {diff} placeholder with the actual diff content
            PROMPT="${PROMPT_TEMPLATE//\{diff\}/}"
            PROMPT+="$DIFF"

            # Use jq to safely construct the JSON payload   for the Gemini API
            JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" \
              '{
                "contents": [
                  {
                    "role": "user",
                    "parts": [ { "text": $prompt } ]
                  }
                ],
                "generation_config": {
                  "temperature": 0.2,
                  "top_p": 0.95,
                  "top_k": 40
                }
              }')

            # Call the model via gcloud, piping the JSON payload to stdin
            gcloud ai models predict gemini-1.5-flash-001 \
              --project=${{ secrets.GCP_PROJECT_ID }} \
              --location=us-central1 \
              --json-request=- <<< "$JSON_PAYLOAD"